const ActionTypes = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SET_TOKEN: 'SET_TOKEN',
  REMOVE_TOKEN: 'REMOVE_TOKEN',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_PROFILE: 'GET_PROFILE',
  GET_SKILLS: 'GET_SKILLS',
  GET_LIST_TUTOR: 'GET_LIST_TUTOR',
  GET_ERROR: 'GET_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  GET_TUTOR_PROFILE: 'GET_TUTOR_PROFILE',
  RENT_TUTOR: 'RENT_TUTOR',
  CREATE_SOCKET: 'CREATE_SOCKET',
  GET_LIST_NOTI: 'GET_LIST_NOTI',
  GET_LIST_HIS: 'GET_LIST_HIS'
};

export default ActionTypes;
